services:
  - type: web
    name: daliz
    env: node
    buildCommand: pnpm install --frozen-lockfile && pnpm --filter daliz-server build
    startCommand: node server/dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: CORS_ORIGIN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
