export { FiadosPage } from './pages/FiadosPage'
export { ClientBalancePage } from './pages/ClientBalancePage'
export { useFiados } from './hooks/useFiados'
export { useFiadosStore } from './store/fiadosStore'
export { clientsService } from './api/clients.service'
export { fiadosService } from './api/fiados.service'
export type { ClientSummary, FiadosState, FiadosActions } from './types'
export type { RegisterPaymentInput } from './api/requests'
export type { ClientListResponse, BalanceDetailResponse } from './api/responses'
